Repository Bluekey-Payment-System/BPS-BE, pull requests merged in 2023-08, with the labels that each got.

#1 BFS-69/dockerfile, docker compose script와 docker container 실행 여부 결과 확인
  .gitignore
  Dockerfile
  docker-compose.yml
  src/main/java/com/github/bluekey/controller/HealthCheckController.java
Labels: API, infra

#2 BPS-62/github action script와 deploy script
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  docker-compose.yml
Labels: infra

#7 BPS-85/OriginalTransaction entity 설계
  src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/exception/transaction/TransactionAlreadyUploadException.java
Labels: enhancement

#8 BPS-83/batch configuration과 dabase strategy
  build.gradle
  src/main/java/com/github/bluekey/batch/config/JobConfig.java
  src/main/java/com/github/bluekey/batch/config/ReaderConfig.java
  src/main/java/com/github/bluekey/batch/config/strategy/H2QueryStrategy.java
  src/main/java/com/github/bluekey/batch/config/strategy/MySQLQueryStrategy.java
  src/main/java/com/github/bluekey/batch/config/strategy/ProfileBasedQueryStrategyProvider.java
  src/main/java/com/github/bluekey/batch/config/strategy/QueryStrategy.java
  src/main/java/com/github/bluekey/batch/config/strategy/QueryStrategyParams.java
  src/main/java/com/github/bluekey/batch/listener/JobCompletionNotificationListener.java
  src/main/java/com/github/bluekey/batch/temp.txt
  src/main/resources/application-local.yml
  src/main/resources/sql/schema-h2.sql
  src/main/resources/sql/schema-mysql.sql
Labels: enhancement

#6 BPS-78/Artist, album, track api swagger 명세 작업
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/controller/track/TrackController.java
  src/main/java/com/github/bluekey/dto/AdminArtistProfileListDto.java
  src/main/java/com/github/bluekey/dto/AlbumBaseDto.java
  src/main/java/com/github/bluekey/dto/AlbumInfoDto.java
  src/main/java/com/github/bluekey/dto/AlbumMonthlyAccontsDto.java
  src/main/java/com/github/bluekey/dto/AlbumMonthlyInfoDto.java
  src/main/java/com/github/bluekey/dto/AlbumMonthlySettlementInfoDto.java
  src/main/java/com/github/bluekey/dto/AlbumMonthlyTrackInfoDto.java
  src/main/java/com/github/bluekey/dto/AlbumTopDto.java
  src/main/java/com/github/bluekey/dto/AlbumTrackAccontsDto.java
  src/main/java/com/github/bluekey/dto/AlbumTrackMonthlyTrendInfoDto.java
  src/main/java/com/github/bluekey/dto/ArtistInfoDto.java
  src/main/java/com/github/bluekey/dto/ArtistMonthlyAccountsDto.java
  src/main/java/com/github/bluekey/dto/ArtistMonthlyAlbumDto.java
  src/main/java/com/github/bluekey/dto/ArtistMonthlyArtistsDto.java
  src/main/java/com/github/bluekey/dto/ArtistMonthlyTrackDto.java
  src/main/java/com/github/bluekey/dto/ArtistMonthlyTrackListDto.java
  src/main/java/com/github/bluekey/dto/ArtistProfileListDto.java
  src/main/java/com/github/bluekey/dto/ArtistRevenueProportionDto.java
  src/main/java/com/github/bluekey/dto/ArtistTrackTopListDto.java
  src/main/java/com/github/bluekey/dto/TrackCommissionRateDto.java
  src/main/java/com/github/bluekey/dto/TrackInfoListDto.java
  src/main/java/com/github/bluekey/dto/TrackParticipantsDto.java
  src/main/java/com/github/bluekey/dto/request/AdminArtistProfileRequestDto.java
  src/main/java/com/github/bluekey/dto/request/AlbumsRequestDto.java
  src/main/java/com/github/bluekey/dto/request/ArtistProfileRequestDto.java
  src/main/java/com/github/bluekey/dto/request/ArtistRequestDto.java
  src/main/java/com/github/bluekey/dto/request/TrackRequestDto.java
  src/main/java/com/github/bluekey/dto/response/AdminArtistProfileListReponseDto.java
  src/main/java/com/github/bluekey/dto/response/AlbumListReponseDto.java
  src/main/java/com/github/bluekey/dto/response/AlbumMonthlyAccontsReponseDto.java
  src/main/java/com/github/bluekey/dto/response/AlbumTopReponseDto.java
  src/main/java/com/github/bluekey/dto/response/AlbumTrackAccontsReponseDto.java
  src/main/java/com/github/bluekey/dto/response/ArtistAlbumsListReponseDto.java
  src/main/java/com/github/bluekey/dto/response/ArtistListReponseDto.java
  src/main/java/com/github/bluekey/dto/response/ArtistMonthlyAccountsReponseDto.java
  src/main/java/com/github/bluekey/dto/response/ArtistMonthlyTrackListReponseDto.java
  src/main/java/com/github/bluekey/dto/response/ArtistTopReponseDto.java
  src/main/java/com/github/bluekey/dto/response/TrackResponseDto.java
Labels: documentation, API

#11 BPS-105/아토유통사 excel file reader와 base validation check logic
  .gitignore
  build.gradle
  src/main/java/com/github/bluekey/controller/transaction/TransactionController.java
  src/main/java/com/github/bluekey/dto/request/transaction/OriginalTransactionRequestDto.java
  src/main/java/com/github/bluekey/dto/response/transaction/OriginalTransactionResponseDto.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
  src/main/java/com/github/bluekey/exception/UploadErrorResponse.java
  src/main/java/com/github/bluekey/exception/transaction/ExcelUploadException.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/ExcelRowException.java
  src/main/java/com/github/bluekey/processor/NameExtractor.java
  src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/provider/ExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/provider/MafiaDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/provider/ThreePointOneFourDistributorExcelProvider.java
  src/main/java/com/github/bluekey/processor/type/AtoExcelColumnType.java
  src/main/java/com/github/bluekey/processor/type/ExcelRowExceptionSeverityType.java
  src/main/java/com/github/bluekey/processor/type/ExcelRowExceptionType.java
  src/main/java/com/github/bluekey/processor/type/ExceptionRule.java
  src/main/java/com/github/bluekey/processor/type/MusicDistributorType.java
  src/main/java/com/github/bluekey/processor/validator/AtoDistributorExcelValidator.java
  src/main/java/com/github/bluekey/processor/validator/ExcelValidator.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
Labels: enhancement, API

#13 BPS-111/Album entity 설계
  src/main/java/com/github/bluekey/entity/album/Album.java
  src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
Labels: enhancement

#14 BPS-125/ Track, TrackMember entity
  src/main/java/com/github/bluekey/entity/album/Album.java
  src/main/java/com/github/bluekey/entity/track/Track.java
  src/main/java/com/github/bluekey/entity/track/TrackMember.java
  src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
  src/main/java/com/github/bluekey/entity/transaction/Transaction.java
  src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
  src/main/java/com/github/bluekey/repository/track/TrackRepository.java
Labels: enhancement

#16 BPS-134/dump용 data.sql
  src/main/resources/application-local.yml
  src/main/resources/sql/data.sql
Labels: database

#17 BPS-135/ DBPersistenceValidator 정의
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
  src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
Labels: enhancement, database

#18 BPS-108/admin 회원가입 api 구현
  src/main/java/com/github/bluekey/BluekeyApplication.java
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/dto/request/SignupRequestDto.java
  src/main/java/com/github/bluekey/dto/response/SignupResponseDto.java
  src/main/java/com/github/bluekey/entity/member/Email.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/entity/member/Password.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#21 BPS-139/ 아토 유통사 엑셀 파일에 대해 DB 데이터 비교 validation
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/NameExtractor.java
  src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
  src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
  src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
  src/main/java/com/github/bluekey/repository/track/TrackRepository.java
  src/main/resources/sql/data.sql
Labels: API, database

#22 BPS-84/Scheduling job config
  build.gradle
  src/main/java/com/github/bluekey/config/ScheduleJobConfig.java
  src/main/java/com/github/bluekey/schedule/job/ExcelToDatabaseJob.java
  src/main/resources/application-local.yml
  src/main/resources/sql/quartz-h2.sql
  src/main/resources/sql/quartz-mysql.sql
Labels: enhancement

#23 BPS-109/스프링 시큐리티 구성 및 로그인 구현
  .gitignore
  build.gradle
  src/main/java/com/github/bluekey/BluekeyApplication.java
  src/main/java/com/github/bluekey/config/SecurityConfig.java
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/dto/JwtInfoDto.java
  src/main/java/com/github/bluekey/dto/LoginMemberDto.java
  src/main/java/com/github/bluekey/dto/response/LoginTokenResponseDto.java
  src/main/java/com/github/bluekey/entity/member/Email.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/jwt/JwtAuthenticationFilter.java
  src/main/java/com/github/bluekey/jwt/JwtProvider.java
  src/main/java/com/github/bluekey/jwt/PrincipalConvertUtil.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/auth/CustomUserDetailsService.java
  src/main/java/com/github/bluekey/service/member/AuthService.java
  src/main/resources/application-local.yml
  src/main/resources/sql/data.sql
Labels: API

#24 BPS-145/계정 리스트 반환 api 명세
  src/main/java/com/github/bluekey/controller/member/MemberController.java
  src/main/java/com/github/bluekey/dto/AdminAccountDto.java
  src/main/java/com/github/bluekey/dto/ArtistAccountDto.java
  src/main/java/com/github/bluekey/dto/response/AdminAccountResponseDto.java
  src/main/java/com/github/bluekey/dto/response/AdminAndArtistAccountResponseDto.java
  src/main/java/com/github/bluekey/dto/response/ArtistAccountResponseDto.java
Labels: documentation

#25 BPS-150/Valid excel file upload
  src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/s3/manager/AwsS3Manager.java
  src/main/java/com/github/bluekey/s3/manager/ResourceManager.java
  src/main/java/com/github/bluekey/s3/manager/S3PrefixType.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
  src/main/resources/application-local.yml
  src/main/resources/sql/data.sql
Labels: enhancement, API

#26 Feature/BaseTimeEntity 설계
  src/main/java/com/github/bluekey/config/JpaAuditingConfig.java
  src/main/java/com/github/bluekey/dto/request/SignupRequestDto.java
  src/main/java/com/github/bluekey/entity/BaseTimeEntity.java
  src/main/java/com/github/bluekey/entity/album/Album.java
  src/main/java/com/github/bluekey/entity/member/Password.java
  src/main/java/com/github/bluekey/entity/track/Track.java
  src/main/java/com/github/bluekey/entity/track/TrackMember.java
  src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
  src/main/java/com/github/bluekey/entity/transaction/Transaction.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
  src/main/resources/sql/data.sql
Labels: API, database

#29 BPS-152/password 관련 api 구현
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/dto/request/PasswordRequestDto.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/exception/member/MemberNotFoundException.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
  src/main/java/com/github/bluekey/service/member/AuthService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#31 BPS-154/슈퍼 어드민이 계정을 삭제하는 API 개발
  src/main/java/com/github/bluekey/config/SecurityConfig.java
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/entity/BaseTimeEntity.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
Labels: API

#30 BPS-162/아티스트 생성 API 개발
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/dto/ArtistAccountDto.java
  src/main/java/com/github/bluekey/dto/LoginMemberDto.java
  src/main/java/com/github/bluekey/dto/request/ArtistRequestDto.java
  src/main/java/com/github/bluekey/dto/request/LoginRequestDto.java
  src/main/java/com/github/bluekey/dto/request/SignupRequestDto.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#33 BPS-157/S3 object processor
  src/main/java/com/github/bluekey/config/SecurityConfig.java
  src/main/java/com/github/bluekey/controller/transaction/TransactionController.java
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/ProcessManager.java
  src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
  src/main/java/com/github/bluekey/validator/annotations/temp.txt
  src/main/java/com/github/bluekey/validator/temp.txt
Labels: API, database

#34 BPS-167/artist profile 업데이트 구현
  src/main/java/com/github/bluekey/config/SecurityConfig.java
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/dto/response/artist/ArtistProfileResponseDto.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/s3/manager/AwsS3Manager.java
  src/main/java/com/github/bluekey/s3/manager/ResourceManager.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
  src/main/java/com/github/bluekey/util/ExcelUploadUtil.java
  src/main/java/com/github/bluekey/util/ImageUploadUtil.java
  src/main/resources/sql/data.sql
Labels: API

#35 BPS-168/admin이 artist의 profile을 변경하는 api 구현
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/dto/artist/ArtistAccountDto.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#36 BPS-158/ato 유통사 엑셀파일에 대한 DB migration
  src/main/java/com/github/bluekey/entity/transaction/ExcelDistributorType.java
  src/main/java/com/github/bluekey/entity/transaction/OriginalTransaction.java
  src/main/java/com/github/bluekey/entity/transaction/Transaction.java
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
  src/main/java/com/github/bluekey/util/ExcelUploadUtil.java
Labels: API, database

#39 Bps 180/어드민 프로필 수정 API 구현
  src/main/java/com/github/bluekey/config/SecurityConfig.java
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#40 BPS-204/login 관련 기능 수정
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/dto/auth/LoginAdminDto.java
  src/main/java/com/github/bluekey/dto/auth/LoginMemberDto.java
  src/main/java/com/github/bluekey/dto/response/auth/AdminLoginTokenResponseDto.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
Labels: bug, API

#47 BPS-210/admin-artist 계정 관리를 위한 API 구현
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/controller/member/MemberController.java
  src/main/java/com/github/bluekey/dto/admin/AdminAccountDto.java
  src/main/java/com/github/bluekey/dto/response/artist/ArtistProfileResponseDto.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#49 BPS-190/Mafia-validation
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/provider/MafiaDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/type/MafiaExcelColumnType.java
  src/main/java/com/github/bluekey/processor/type/MusicDistributorType.java
  src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
  src/main/java/com/github/bluekey/processor/validator/DistributorExcelValidator.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
  src/main/resources/sql/data.sql
Labels: API, database

#50 BPS-216/Track 생성 API
  src/main/java/com/github/bluekey/controller/track/TrackController.java
  src/main/java/com/github/bluekey/dto/request/track/TrackRequestDto.java
  src/main/java/com/github/bluekey/dto/response/track/TrackResponseDto.java
  src/main/java/com/github/bluekey/dto/track/TrackCommissionRateDto.java
  src/main/java/com/github/bluekey/entity/track/TrackMember.java
  src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
  src/main/java/com/github/bluekey/service/track/TrackService.java
  src/main/resources/application-local.yml
Labels: API

#51 BPS-217/Track 삭제 API 수정
  src/main/java/com/github/bluekey/controller/track/TrackController.java
  src/main/java/com/github/bluekey/service/track/TrackService.java
Labels: API

#52 BPS-218/드롭다운 UI용 아티스트 리스트 조회 API
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/dto/artist/SimpleArtistAccountDto.java
  src/main/java/com/github/bluekey/dto/response/artist/SimpleArtistAccountListResponseDto.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#53 BPS223/업로드된 엑셀파일 조회 API
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/exception/transaction/AlreadyOriginalTransactionExistException.java
  src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
Labels: API

#54 BPS-224/엑셀 파일 삭제 API
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
  src/main/java/com/github/bluekey/util/ExcelUploadUtil.java
Labels: API

#56 BPS-225/앨범 생성
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/response/album/AlbumResponseDto.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/album/AlbumService.java
  src/main/java/com/github/bluekey/util/ImageUploadUtil.java
Labels: API

#57 BPS-228/admin-check api
  src/main/java/com/github/bluekey/config/SecurityConfig.java
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
  src/main/java/com/github/bluekey/jwt/JwtAuthenticationFilter.java
Labels: API

#64 BPS-232/album donut API
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/album/AlbumTopDto.java
  src/main/java/com/github/bluekey/dto/response/album/AlbumTopResponseDto.java
  src/main/java/com/github/bluekey/service/dashboard/DashBoardService.java
Labels: API

#65 BPS-233/아티스트 기준 Top tracks 조회 API
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/service/dashboard/TopTrackDashBoardService.java
Labels: API

#66 BPS-234/admin dashboard summary
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/dto/response/common/DashboardTotalInfoResponseDto.java
  src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java
Labels: API

#67 BPS-235/Album summary API
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/response/album/AlbumSummaryResponseDto.java
  src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java
Labels: API

#69 BPS-237/Artist dashboard summary 조회 API
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/dto/response/artist/ArtistSummaryResponseDto.java
  src/main/java/com/github/bluekey/entity/transaction/Transaction.java
  src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java
Labels: API

#68 BPS-238/앨범 리스트 조회 API
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/album/AlbumInfoDto.java
  src/main/java/com/github/bluekey/dto/response/artist/ArtistAlbumsListResponseDto.java
  src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
  src/main/java/com/github/bluekey/repository/track/TrackMemberRepository.java
  src/main/java/com/github/bluekey/service/album/AlbumService.java
Labels: API

#70 BPS-239/album bar chart 조회 API 구현
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/album/AlbumMonthlyAccountsDto.java
  src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
  src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
Labels: API

#71 BPS-244/트랙별 추이 조회 API 구현
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/album/AlbumTrackMonthlyTrendInfoDto.java
  src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
  src/main/java/com/github/bluekey/service/dashboard/LineChartDashBoardService.java
Labels: API

#72 BPS-243/월별 매출-정산액 조회 API 구현
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/dto/artist/ArtistMonthlyAccountsDto.java
  src/main/java/com/github/bluekey/dto/common/MonthlyTrendDto.java
  src/main/java/com/github/bluekey/dto/response/common/MonthlyTrendResponseDto.java
  src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
Labels: API

#73 BPS-240/월별 트랙 페이지네이션 API
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/dto/common/MemberBaseDto.java
  src/main/java/com/github/bluekey/dto/response/track/TracksSettlementAmountResponseDto.java
  src/main/java/com/github/bluekey/dto/track/TrackSettlementAmountDto.java
  src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java
Labels: API

#74 BPS-246/artist track monthly API
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/dto/artist/ArtistMonthlyArtistsDto.java
  src/main/java/com/github/bluekey/dto/artist/ArtistMonthlyTrackListDto.java
  src/main/java/com/github/bluekey/dto/response/artist/ArtistMonthlyTrackListResponseDto.java
  src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java
Labels: API

#77 BPS-255/파일 업로드 시 메일 전송 로직 추가
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
Labels: API

#79 BPS-256/아티스트 현황 조회 API
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/dto/admin/AdminArtistProfileListDto.java
  src/main/java/com/github/bluekey/dto/response/admin/AdminArtistProfileListReponseDto.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/dashboard/TopTrackDashBoardService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API
