Repository Bluekey-Payment-System/BPS-BE, pull requests merged in 2023-10, with the labels that each got.

#122 BPS-367/Dashboard transaction 전략 패턴 개발 건
  src/main/java/com/github/bluekey/service/dashboard/v2/DashboardCalculationService.java
  src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionAdminClient.java
  src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionArtistClient.java
  src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionFactory.java
  src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionAllStrategy.java
  src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionFilteringStrategy.java
  src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionGroupingStrategy.java
  src/main/java/com/github/bluekey/service/dashboard/v2/strategy/DashboardTransactionSortingStrategy.java
Labels: refactoring

#123 BPS-368/service layer versioning과 DateUtil class 정의
  src/main/java/com/github/bluekey/service/dashboard/v2/BarChardDashboardServiceV2.java
  src/main/java/com/github/bluekey/service/dashboard/v2/LineChartDashBoardServiceV2.java
  src/main/java/com/github/bluekey/service/dashboard/v2/MonthlyTracksDashboardServiceV2.java
  src/main/java/com/github/bluekey/service/dashboard/v2/SummaryDashBoardServiceV2.java
  src/main/java/com/github/bluekey/service/dashboard/v2/TopTrackDashBoardServiceV2.java
  src/main/java/com/github/bluekey/util/DateUtil.java
Labels: refactoring

#125 BPS-369/DashboardTransactionAdminClient
  src/main/java/com/github/bluekey/service/dashboard/v2/BarChardDashboardServiceV2.java
  src/main/java/com/github/bluekey/service/dashboard/v2/BarChartDashboardServiceV2.java
  src/main/java/com/github/bluekey/service/dashboard/v2/DashboardTransactionAdminClient.java
Labels: enhancement, refactoring

#124 Feat/request authority
  src/main/java/com/github/bluekey/controller/notification/NotificationController.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
Labels: API

#128 PENDING status request authority 존재 여부 반환 API
  src/main/java/com/github/bluekey/controller/notification/NotificationController.java
  src/main/java/com/github/bluekey/dto/response/RequestAuthorityPendingStatusResponseDto.java
  src/main/java/com/github/bluekey/entity/member/MemberRole.java
  src/main/java/com/github/bluekey/entity/notification/RequestStatus.java
  src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java
Labels: API

#129 Request Authority 승인과 거절 API Response
  src/main/java/com/github/bluekey/controller/notification/NotificationController.java
  src/main/java/com/github/bluekey/dto/response/RequestAuthorityUpdateResponseDto.java
  src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java
Labels: API
