Repository Bluekey-Payment-System/BPS-BE, pull requests merged in 2023-09, with the labels that each got.

#82 BPS-279/sentry integration
  build.gradle
  src/main/java/com/github/bluekey/controller/SentryCheckController.java
Labels: enhancement

#84 BPS-299/Slack API연동과 Sentry config
  build.gradle
  src/main/java/com/github/bluekey/controller/SentryCheckController.java
  src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
  src/main/java/com/github/bluekey/util/SlackUtil.java
  src/main/resources/application-local.yml
Labels: enhancement, API

#83 BPS-264(BPS-291)/앨범 수정 API 구현
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/response/album/AlbumResponseDto.java
  src/main/java/com/github/bluekey/service/album/AlbumService.java
Labels: API

#80 Hotfix/permission
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/service/album/AlbumService.java
  src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
  src/main/java/com/github/bluekey/service/dashboard/LineChartDashBoardService.java
  src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java
  src/main/java/com/github/bluekey/service/dashboard/TopTrackDashBoardService.java
Labels: API

#87 BPS-309/transaction response format 변경
  src/main/java/com/github/bluekey/exception/transaction/ExcelUploadException.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
Labels: API

#89 BPS-288/Transcation exception 정의
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
Labels: refactoring

#90 BPS-284/member exception 정의
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
  src/main/java/com/github/bluekey/service/auth/CustomUserDetailsService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: refactoring

#92 BPS-317/JWT validation
  build.gradle
  src/main/java/com/github/bluekey/config/security/SecurityConfig.java
  src/main/java/com/github/bluekey/config/security/jwt/JWTAuthenticationEntryPoint.java
  src/main/java/com/github/bluekey/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/github/bluekey/config/security/jwt/JwtProvider.java
  src/main/java/com/github/bluekey/config/security/jwt/JwtValidationType.java
  src/main/java/com/github/bluekey/config/security/jwt/PrincipalConvertUtil.java
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
  src/main/java/com/github/bluekey/exception/UploadErrorResponse.java
  src/main/java/com/github/bluekey/jwt/JwtAuthenticationFilter.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
Labels: enhancement

#93 Deploy
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy.yml
  build.gradle
  src/main/java/com/github/bluekey/config/security/SecurityConfig.java
  src/main/java/com/github/bluekey/config/security/jwt/JWTAuthenticationEntryPoint.java
  src/main/java/com/github/bluekey/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/github/bluekey/config/security/jwt/JwtProvider.java
  src/main/java/com/github/bluekey/config/security/jwt/JwtValidationType.java
  src/main/java/com/github/bluekey/config/security/jwt/PrincipalConvertUtil.java
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/exception/GlobalExceptionHandler.java
  src/main/java/com/github/bluekey/exception/UploadErrorResponse.java
  src/main/java/com/github/bluekey/jwt/JwtAuthenticationFilter.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/repository/transaction/OriginalTransactionRepository.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
  src/main/java/com/github/bluekey/service/auth/CustomUserDetailsService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
Labels: Deploy

#91 BPS-282/dashboard util 생성
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/dto/album/AlbumTopDto.java
  src/main/java/com/github/bluekey/dto/album/AlbumTrackMonthlyTrendInfoDto.java
  src/main/java/com/github/bluekey/dto/album/AlbumTrackTrendDto.java
  src/main/java/com/github/bluekey/dto/artist/ArtistMonthlyTrackListDto.java
  src/main/java/com/github/bluekey/dto/common/AlbumBaseDto.java
  src/main/java/com/github/bluekey/dto/common/MonthlyTrendDto.java
  src/main/java/com/github/bluekey/dto/common/TotalAndGrowthDto.java
  src/main/java/com/github/bluekey/dto/common/TrackBaseDto.java
  src/main/java/com/github/bluekey/dto/response/album/AlbumTrackTrendResponseDto.java
  src/main/java/com/github/bluekey/dto/track/TrackSettlementAmountDto.java
  src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
  src/main/java/com/github/bluekey/service/dashboard/DashboardUtilService.java
  src/main/java/com/github/bluekey/service/dashboard/LineChartDashBoardService.java
  src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java
  src/main/java/com/github/bluekey/service/dashboard/SummaryDashBoardService.java
  src/main/java/com/github/bluekey/service/dashboard/TopTrackDashBoardService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
  src/main/java/com/github/bluekey/util/DashboardUtil.java
Labels: refactoring

#94 BPS-285/album exception refactoring
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/service/album/AlbumService.java
Labels: refactoring

#96 BPS-313/dashboard monthly tracks filtering, sorting
  src/main/java/com/github/bluekey/controller/member/AdminController.java
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/dto/filter/MonthlyTrackFilter.java
  src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java
Labels: API

#97 BPS-298/유저 프로필 이미지 삭제 api 추가
  src/main/java/com/github/bluekey/controller/member/ArtistController.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
Labels: API

#98 BPS-297/앨범 이미지 삭제 api 구현
  src/main/java/com/github/bluekey/controller/album/AlbumController.java
  src/main/java/com/github/bluekey/service/album/AlbumService.java
  src/main/resources/application-local.yml
Labels: API

#100 BPS-300/어드민이 비밀번호 재발급해주는 api 구현
  src/main/java/com/github/bluekey/controller/member/AuthController.java
  src/main/java/com/github/bluekey/dto/response/auth/NewPasswordResponseDto.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
Labels: API

#101 BPS-303/마피아 유통사 정산내역 파일 validation
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/provider/MafiaDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
Labels: API

#102 BPS-304/Mafia excel file migration
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/repository/album/AlbumRepository.java
  src/main/java/com/github/bluekey/repository/track/TrackRepository.java
  src/main/resources/sql/data.sql
Labels: enhancement

#103 BPS-324/Transaction table schema
  src/main/java/com/github/bluekey/entity/track/Track.java
  src/main/java/com/github/bluekey/entity/transaction/Transaction.java
Labels: refactoring

#104 BPS-325/migration
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/processor/ExcelFileProcessManager.java
  src/main/java/com/github/bluekey/processor/provider/AtoDistributorExcelFileProvider.java
  src/main/java/com/github/bluekey/processor/validator/DBPersistenceValidator.java
  src/main/java/com/github/bluekey/processor/validator/DistributorExcelValidator.java
  src/main/java/com/github/bluekey/repository/track/TrackRepository.java
  src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
  src/main/java/com/github/bluekey/service/transaction/TransactionService.java
  src/main/resources/sql/data.sql
Labels: refactoring

#105 BPS-328/Transaction table format 변경에 따른 대시보드 계산 로직 변경
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/repository/track/TrackRepository.java
  src/main/java/com/github/bluekey/service/dashboard/DashboardUtilService.java
Labels: refactoring

#106 BPS-290/Track 수정 API
  src/main/java/com/github/bluekey/controller/track/TrackController.java
  src/main/java/com/github/bluekey/entity/track/Track.java
  src/main/java/com/github/bluekey/service/track/TrackService.java
Labels: API

#110 BPS-315/1차 docs
  README.md
  docs/images/infra.png
  docs/images/logo.png
Labels: enhancement

#111 BPS-316/2차 docs
  README.md
  docs/images/bluekey_erd.png
  docs/images/server.png
Labels: documentation

#115 BPS-350/Dashboard 데이터 연산식 관리 class 분리
  src/main/java/com/github/bluekey/service/dashboard/DashboardCalculationService.java
Labels: refactoring

#116 BPS-353/FEAT: request authority entity 생성
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/entity/notification/MemberRequestAuthority.java
  src/main/java/com/github/bluekey/entity/notification/RequestAuthority.java
  src/main/java/com/github/bluekey/entity/notification/RequestStatus.java
Labels: API, database

#117 BPS-359/Transaction trackMember field 참조 로직 제거
  src/main/java/com/github/bluekey/entity/track/TrackMember.java
  src/main/java/com/github/bluekey/entity/transaction/Transaction.java
  src/main/java/com/github/bluekey/processor/ExcelFileDBMigrationProcessManager.java
  src/main/java/com/github/bluekey/repository/transaction/TransactionRepository.java
  src/main/java/com/github/bluekey/service/dashboard/BarChartDashboardService.java
  src/main/java/com/github/bluekey/service/dashboard/LineChartDashBoardService.java
  src/main/java/com/github/bluekey/service/dashboard/MonthlyTracksDashBoardService.java
Labels: refactoring

#118 BPS-354/FEAT: 어드민 회원 가입시 권한 요청하도록 구현
  src/main/java/com/github/bluekey/dto/swagger/request/auth/SignupRequestDto.java
  src/main/java/com/github/bluekey/entity/member/MemberRole.java
  src/main/java/com/github/bluekey/mail/EmailService.java
  src/main/java/com/github/bluekey/repository/member/MemberRepository.java
  src/main/java/com/github/bluekey/repository/notification/MemberRequestAuthorityRepository.java
  src/main/java/com/github/bluekey/repository/notification/RequestAuthorityRepository.java
  src/main/java/com/github/bluekey/service/auth/AuthService.java
  src/main/java/com/github/bluekey/service/member/MemberService.java
  src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java
  src/main/resources/application-local.yml
Labels: API

#119 BPS-355/FEAT: 권한 요청 승인 API 구현
  src/main/java/com/github/bluekey/controller/notification/NotificationController.java
  src/main/java/com/github/bluekey/entity/member/Member.java
  src/main/java/com/github/bluekey/exception/ErrorCode.java
  src/main/java/com/github/bluekey/repository/notification/MemberRequestAuthorityRepository.java
  src/main/java/com/github/bluekey/repository/notification/RequestAuthorityRepository.java
  src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java
Labels: API

#121 BPS-356/FEAT: 권한 요청 거절 API 구현
  src/main/java/com/github/bluekey/controller/notification/NotificationController.java
  src/main/java/com/github/bluekey/service/notification/RequestAuthorityService.java
Labels: API
